package com.brandslink.cloud.inbound.entity;

import java.io.Serializable;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  box_info
 * @author zc
 * @date 2019-07-23 10:34:39
 */
@ApiModel(value ="BoxInfo")
public class BoxInfo implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "仓库")
    private String warehouse;

    @ApiModelProperty(value = "楼层")
    private String floor;

    @ApiModelProperty(value = "箱子类型  a 楼层箱   b 货列箱")
    private String type;

    @ApiModelProperty(value = "箱号")
    private String boxId;

    @ApiModelProperty(value = "货列号")
    private String listId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table box_info
     *
     * @mbg.generated 2019-07-23 10:34:39
     */
    private static final long serialVersionUID = 1L;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getWarehouse() {
		return warehouse;
	}

	public void setWarehouse(String warehouse) {
		this.warehouse = warehouse;
	}

	public String getFloor() {
		return floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getBoxId() {
		return boxId;
	}

	public void setBoxId(String boxId) {
		this.boxId = boxId;
	}

	public String getListId() {
		return listId;
	}

	public void setListId(String listId) {
		this.listId = listId;
	}

    
    
    
    
    
    
    
}