package com.brandslink.cloud.inbound.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  putaway_exception
 * @author zhaojiaxing
 * @date 2019-06-15 11:18:14
 */
@ApiModel(value ="PutawayException")
public class PutawayException implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "运单号")
    private String waybillNumber;

    @ApiModelProperty(value = "上架单id")
    private String putawayId;

    @ApiModelProperty(value = "货列箱号")
    private String listBoxId;
    
    @ApiModelProperty(value = "货位编码")
    private String recommendedLocationCode;

    @ApiModelProperty(value = "sku")
    private String sku;

    @ApiModelProperty(value = "异常原因")
    private String exceptionCause;

    @ApiModelProperty(value = "数量")
    private Integer amount;

    @ApiModelProperty(value = "异常箱号")
    private String exceptionBoxId;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "创建人")
    private String creater;

    @ApiModelProperty(value = "创建人id")
    private Integer createrId;

    @ApiModelProperty(value = "仓库")
    private String warehouseCode;
    
    
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table putaway_exception
     *
     * @mbg.generated 2019-06-15 11:18:14
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
   

	public String getRecommendedLocationCode() {
		return recommendedLocationCode;
	}

	public void setRecommendedLocationCode(String recommendedLocationCode) {
		this.recommendedLocationCode = recommendedLocationCode;
	}

	public String getWaybillNumber() {
        return waybillNumber;
    }

    public void setWaybillNumber(String waybillNumber) {
        this.waybillNumber = waybillNumber == null ? null : waybillNumber.trim();
    }

    public String getPutawayId() {
        return putawayId;
    }

    public void setPutawayId(String putawayId) {
        this.putawayId = putawayId == null ? null : putawayId.trim();
    }

    public String getListBoxId() {
        return listBoxId;
    }

    public void setListBoxId(String listBoxId) {
        this.listBoxId = listBoxId == null ? null : listBoxId.trim();
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    public String getExceptionCause() {
        return exceptionCause;
    }

    public void setExceptionCause(String exceptionCause) {
        this.exceptionCause = exceptionCause == null ? null : exceptionCause.trim();
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public String getExceptionBoxId() {
        return exceptionBoxId;
    }

    public void setExceptionBoxId(String exceptionBoxId) {
        this.exceptionBoxId = exceptionBoxId == null ? null : exceptionBoxId.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getCreater() {
        return creater;
    }

    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    public Integer getCreaterId() {
        return createrId;
    }

    public void setCreaterId(Integer createrId) {
        this.createrId = createrId;
    }

	public String getWarehouseCode() {
		return warehouseCode;
	}

	public void setWarehouseCode(String warehouseCode) {
		this.warehouseCode = warehouseCode;
	}

    
    
    
    
}