package com.brandslink.cloud.inbound.entity;

import java.io.Serializable;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  putaway_strategy
 * @author zc
 * @date 2019-06-14 13:47:46
 */
@ApiModel(value ="PutawayStrategy")
public class PutawayStrategy implements Serializable {
    @ApiModelProperty(value = "id")
    private Integer id;

    @ApiModelProperty(value = "策略名称")
    private String strategyName;

    @ApiModelProperty(value = "策略规则")
    private String strategyRule;

    @ApiModelProperty(value = "适用仓库")
    private String warehouse;

    @ApiModelProperty(value = "仓库Codes集合")
    private List<String> warehouseCodes;

    @ApiModelProperty(value = "货主")
    private String shipper;

    @ApiModelProperty(value = "状态 ( 1. 启用  2. 停用)")
    private String status;

    @ApiModelProperty(value = "描述")
    private String comment;

    @ApiModelProperty(value = "创建人")
    private String creater;

    @ApiModelProperty(value = "创建人id")
    private Integer createrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table putaway_strategy
     *
     * @mbg.generated 2019-06-14 13:47:46
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStrategyName() {
        return strategyName;
    }

    public void setStrategyName(String strategyName) {
        this.strategyName = strategyName == null ? null : strategyName.trim();
    }

    public String getStrategyRule() {
        return strategyRule;
    }

    public void setStrategyRule(String strategyRule) {
        this.strategyRule = strategyRule == null ? null : strategyRule.trim();
    }

    public String getWarehouse() {
        return warehouse;
    }

    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse == null ? null : warehouse.trim();
    }

    public List<String> getWarehouseCodes() {
        return warehouseCodes;
    }

    public void setWarehouseCodes(List<String> warehouseCodes) {
        this.warehouseCodes = warehouseCodes;
    }

    public String getShipper() {
        return shipper;
    }

    public void setShipper(String shipper) {
        this.shipper = shipper == null ? null : shipper.trim();
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    public String getCreater() {
        return creater;
    }

    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    public Integer getCreaterId() {
        return createrId;
    }

    public void setCreaterId(Integer createrId) {
        this.createrId = createrId;
    }
}