package com.brandslink.cloud.inbound.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 上架策略分配表
 * 实体类对应的数据表为：  t_putaway_shelf
 * @author zc
 * @date 2019-07-19 15:46:15
 */
@ApiModel(value ="PutawayShelf")
public class PutawayShelf implements Serializable {
    @ApiModelProperty(value = "主键id")
    private Long sid;

    @ApiModelProperty(value = "运单号")
    private String waybillNumber;

    @ApiModelProperty(value = "商品sku")
    private String sku;

    @ApiModelProperty(value = "sku剩余数量")
    private Integer skuRemainNum;

    @ApiModelProperty(value = "计划上架数")
    private Integer plannedPutawayNumber;

    @ApiModelProperty(value = "仓库编码")
    private String warehouseCode;

    @ApiModelProperty(value = "sku存放的楼层")
    private String skuFloor;

    @ApiModelProperty(value = "推荐货位编码")
    private String recommendedLocationCode;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    @ApiModelProperty(value = "版本号")
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_putaway_shelf
     *
     * @mbg.generated 2019-07-19 15:46:15
     */
    private static final long serialVersionUID = 1L;

    public Long getSid() {
        return sid;
    }

    public void setSid(Long sid) {
        this.sid = sid;
    }

    public String getWaybillNumber() {
        return waybillNumber;
    }

    public void setWaybillNumber(String waybillNumber) {
        this.waybillNumber = waybillNumber == null ? null : waybillNumber.trim();
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    public Integer getSkuRemainNum() {
        return skuRemainNum;
    }

    public void setSkuRemainNum(Integer skuRemainNum) {
        this.skuRemainNum = skuRemainNum;
    }

    public Integer getPlannedPutawayNumber() {
        return plannedPutawayNumber;
    }

    public void setPlannedPutawayNumber(Integer plannedPutawayNumber) {
        this.plannedPutawayNumber = plannedPutawayNumber;
    }

    public String getWarehouseCode() {
        return warehouseCode;
    }

    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
    }

    public String getSkuFloor() {
        return skuFloor;
    }

    public void setSkuFloor(String skuFloor) {
        this.skuFloor = skuFloor == null ? null : skuFloor.trim();
    }

    public String getRecommendedLocationCode() {
        return recommendedLocationCode;
    }

    public void setRecommendedLocationCode(String recommendedLocationCode) {
        this.recommendedLocationCode = recommendedLocationCode == null ? null : recommendedLocationCode.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
}