package com.brandslink.cloud.inbound.entity;

import java.io.Serializable;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  t_quality_box_assistants
 * @author zhaojiaxing
 * @date 2019-08-02 14:35:14
 */
@ApiModel(value ="QualityBoxAssistants")
public class QualityBoxAssistants implements Serializable {
    @ApiModelProperty(value = "主键id")
    private Long sid;

    @ApiModelProperty(value = "封箱表外键")
    private Long boxSid;

    @ApiModelProperty(value = "协助人表外键")
    private Long assistantsSid;

    @ApiModelProperty(value = "封箱数")
    private Integer sealNum;

    @ApiModelProperty(value = "版本号")
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_quality_box_assistants
     *
     * @mbg.generated 2019-08-02 14:35:14
     */
    private static final long serialVersionUID = 1L;

    public Long getSid() {
        return sid;
    }

    public void setSid(Long sid) {
        this.sid = sid;
    }

    public Long getBoxSid() {
        return boxSid;
    }

    public void setBoxSid(Long boxSid) {
        this.boxSid = boxSid;
    }

    public Long getAssistantsSid() {
        return assistantsSid;
    }

    public void setAssistantsSid(Long assistantsSid) {
        this.assistantsSid = assistantsSid;
    }

    public Integer getSealNum() {
        return sealNum;
    }

    public void setSealNum(Integer sealNum) {
        this.sealNum = sealNum;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
}