package com.brandslink.cloud.inbound.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 质检详情协同人
 * 实体类对应的数据表为：  t_quality_control_assistants
 * @author zhaojiaxing
 * @date 2019-07-06 11:56:10
 */
@ApiModel(value ="QualityControlAssistants")
public class QualityControlAssistants implements Serializable {
    @ApiModelProperty(value = "主键id")
    private Long sid;

    @ApiModelProperty(value = "运单号")
    private String waybillNumber;

    @ApiModelProperty(value = "商品sku")
    private String sku;

    @ApiModelProperty(value = "sku剩余数量")
    private Integer skuRemainNum;

    @ApiModelProperty(value = "质检数量")
    private Integer qcNumber;

    @ApiModelProperty(value = "推荐货位编码")
    private String recommendedLocationCode;

    @ApiModelProperty(value = "质检台id")
    private String qcStationId;

    @ApiModelProperty(value = "协同人")
    private String assistants;

    @ApiModelProperty(value = "质检人id")
    private Long createId;

    @ApiModelProperty(value = "质检人")
    private String createName;

    @ApiModelProperty(value = "质检时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date skuCreateTime;

    @ApiModelProperty(value = "版本号")
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_quality_control_assistants
     *
     * @mbg.generated 2019-07-06 11:56:10
     */
    private static final long serialVersionUID = 1L;

    public Long getSid() {
        return sid;
    }

    public void setSid(Long sid) {
        this.sid = sid;
    }

    public String getWaybillNumber() {
        return waybillNumber;
    }

    public void setWaybillNumber(String waybillNumber) {
        this.waybillNumber = waybillNumber == null ? null : waybillNumber.trim();
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    public Integer getSkuRemainNum() {
        return skuRemainNum;
    }

    public void setSkuRemainNum(Integer skuRemainNum) {
        this.skuRemainNum = skuRemainNum;
    }

    public Integer getQcNumber() {
        return qcNumber;
    }

    public void setQcNumber(Integer qcNumber) {
        this.qcNumber = qcNumber;
    }

    public String getRecommendedLocationCode() {
        return recommendedLocationCode;
    }

    public void setRecommendedLocationCode(String recommendedLocationCode) {
        this.recommendedLocationCode = recommendedLocationCode;
    }

    public String getQcStationId() {
        return qcStationId;
    }

    public void setQcStationId(String qcStationId) {
        this.qcStationId = qcStationId == null ? null : qcStationId.trim();
    }

    public String getAssistants() {
        return assistants;
    }

    public void setAssistants(String assistants) {
        this.assistants = assistants == null ? null : assistants.trim();
    }

    public Long getCreateId() {
        return createId;
    }

    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public String getCreateName() {
        return createName;
    }

    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getSkuCreateTime() {
        return skuCreateTime;
    }

    public void setSkuCreateTime(Date skuCreateTime) {
        this.skuCreateTime = skuCreateTime;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
}