package com.brandslink.cloud.inbound.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 质检封箱表
 * 实体类对应的数据表为：  t_quality_box_putaway
 * @author zc
 * @date 2019-07-31 16:02:29
 */
@ApiModel(value ="QualityBoxPutaway")
public class QualityBoxPutaway implements Serializable {
    @ApiModelProperty(value = "主键id")
    private Long sid;

    @ApiModelProperty(value = "上架单号")
    private String putawayId;

    @ApiModelProperty(value = "仓库")
    private String warehouseCode;

    @ApiModelProperty(value = "质检箱箱号")
    private String sealBoxSerialNumber;

    @ApiModelProperty(value = "运单号")
    private String waybillNumber;

    @ApiModelProperty(value = "商品sku")
    private String sku;

    @ApiModelProperty(value = "封箱楼层（对应sku楼层）")
    private String skuFloor;

    @ApiModelProperty(value = "楼层箱号")
    private String floorBoxNumber;

    @ApiModelProperty(value = "货列箱号")
    private String listBoxNumber;

    @ApiModelProperty(value = "计划上架数量（箱内该sku商品数量）")
    private Integer plannedPutawayNumber;

    @ApiModelProperty(value = "实际上架数量")
    private Integer actualPutawayNumber;

    @ApiModelProperty(value = "推荐货位")
    private String recommendedLocationCode;

    @ApiModelProperty(value = "实际上架货位")
    private String actualLocationCode;

    @ApiModelProperty(value = "质检箱封箱创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "上架时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date putawayTime;

    @ApiModelProperty(value = "上架人")
    private String operator;

    @ApiModelProperty(value = "上架人id")
    private Integer operatorId;

    @ApiModelProperty(value = "sku上架状态   0 未上架   1 已上架 ")
    private Integer status;
    
    @ApiModelProperty(value = "查询类型")
    private String type;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_quality_box_putaway
     *
     * @mbg.generated 2019-07-31 16:02:29
     */
    private static final long serialVersionUID = 1L;

    public Long getSid() {
        return sid;
    }

    public void setSid(Long sid) {
        this.sid = sid;
    }

    public String getPutawayId() {
        return putawayId;
    }

    public void setPutawayId(String putawayId) {
        this.putawayId = putawayId == null ? null : putawayId.trim();
    }

    public String getWarehouseCode() {
        return warehouseCode;
    }

    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
    }

    public String getSealBoxSerialNumber() {
        return sealBoxSerialNumber;
    }

    public void setSealBoxSerialNumber(String sealBoxSerialNumber) {
        this.sealBoxSerialNumber = sealBoxSerialNumber == null ? null : sealBoxSerialNumber.trim();
    }

    public String getWaybillNumber() {
        return waybillNumber;
    }

    public void setWaybillNumber(String waybillNumber) {
        this.waybillNumber = waybillNumber == null ? null : waybillNumber.trim();
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    public String getSkuFloor() {
        return skuFloor;
    }

    public void setSkuFloor(String skuFloor) {
        this.skuFloor = skuFloor == null ? null : skuFloor.trim();
    }

    public String getFloorBoxNumber() {
        return floorBoxNumber;
    }

    public void setFloorBoxNumber(String floorBoxNumber) {
        this.floorBoxNumber = floorBoxNumber == null ? null : floorBoxNumber.trim();
    }

    public String getListBoxNumber() {
        return listBoxNumber;
    }

    public void setListBoxNumber(String listBoxNumber) {
        this.listBoxNumber = listBoxNumber == null ? null : listBoxNumber.trim();
    }

    public Integer getPlannedPutawayNumber() {
        return plannedPutawayNumber;
    }

    public void setPlannedPutawayNumber(Integer plannedPutawayNumber) {
        this.plannedPutawayNumber = plannedPutawayNumber;
    }

    public Integer getActualPutawayNumber() {
        return actualPutawayNumber;
    }

    public void setActualPutawayNumber(Integer actualPutawayNumber) {
        this.actualPutawayNumber = actualPutawayNumber;
    }

    public String getRecommendedLocationCode() {
        return recommendedLocationCode;
    }

    public void setRecommendedLocationCode(String recommendedLocationCode) {
        this.recommendedLocationCode = recommendedLocationCode == null ? null : recommendedLocationCode.trim();
    }

    public String getActualLocationCode() {
        return actualLocationCode;
    }

    public void setActualLocationCode(String actualLocationCode) {
        this.actualLocationCode = actualLocationCode == null ? null : actualLocationCode.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getPutawayTime() {
        return putawayTime;
    }

    public void setPutawayTime(Date putawayTime) {
        this.putawayTime = putawayTime;
    }

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    public Integer getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
    
    
    
    
}