package com.brandslink.cloud.inbound.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 质检详情表
 * 实体类对应的数据表为：  t_quality_control_details
 * @author zhaojiaxing
 * @date 2019-07-05 10:39:34
 */
@ApiModel(value ="QualityControlDetails")
public class QualityControlDetails implements Serializable {
    @ApiModelProperty(value = "主键id")
    private Long sid;

    @ApiModelProperty(value = "图片路径")
    private String pictureUrl;

    @ApiModelProperty(value = "质检单号（系统自动生成，QC+年（后两位）+月+日+六位流水）")
    private String qualityControlOrderNumber;

    @ApiModelProperty(value = "来源单号")
    private String sourceOrderNumber;

    @ApiModelProperty(value = "运单号，SKU对应所在的承运商单号")
    private String waybillNumber;

    @ApiModelProperty(value = "商品sku")
    private String sku;

    @ApiModelProperty(value = "质检良品数")
    private Integer goodProductNumber;

    @ApiModelProperty(value = "质检次品数")
    private Integer unusableProductNumber;

    @ApiModelProperty(value = "qc完成数量")
    private Integer qualityControlFinishNumber;

    @ApiModelProperty(value = "已封箱数量")
    private Integer sealBoxFinishNumber;

    @ApiModelProperty(value = "qc未封箱数量")
    private Integer sealBoxUnfinishNumber;

    @ApiModelProperty(value = "SKU单据状态(1:待质检；2:质检中；3:质检完成)")
    private Byte skuStatus;

    @ApiModelProperty(value = "质检创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date skuCreateTime;

    @ApiModelProperty(value = "质检更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date skuUpdateTime;

    @ApiModelProperty(value = "否存在异常(0:不存在；1:存在)")
    private Byte isExceptionCase;

    @ApiModelProperty(value = "sku对应的楼层")
    private String skuFloor;

    @ApiModelProperty(value = "预留字段1")
    private String reserved;

    @ApiModelProperty(value = "备注")
    private String remark;

    @ApiModelProperty(value = "版本号")
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_quality_control_details
     *
     * @mbg.generated 2019-07-05 10:39:34
     */
    private static final long serialVersionUID = 1L;

    public Long getSid() {
        return sid;
    }

    public void setSid(Long sid) {
        this.sid = sid;
    }

    public String getPictureUrl() {
        return pictureUrl;
    }

    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    public String getQualityControlOrderNumber() {
        return qualityControlOrderNumber;
    }

    public void setQualityControlOrderNumber(String qualityControlOrderNumber) {
        this.qualityControlOrderNumber = qualityControlOrderNumber == null ? null : qualityControlOrderNumber.trim();
    }

    public String getSourceOrderNumber() {
        return sourceOrderNumber;
    }

    public void setSourceOrderNumber(String sourceOrderNumber) {
        this.sourceOrderNumber = sourceOrderNumber == null ? null : sourceOrderNumber.trim();
    }

    public String getWaybillNumber() {
        return waybillNumber;
    }

    public void setWaybillNumber(String waybillNumber) {
        this.waybillNumber = waybillNumber == null ? null : waybillNumber.trim();
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    public Integer getGoodProductNumber() {
        return goodProductNumber;
    }

    public void setGoodProductNumber(Integer goodProductNumber) {
        this.goodProductNumber = goodProductNumber;
    }

    public Integer getUnusableProductNumber() {
        return unusableProductNumber;
    }

    public void setUnusableProductNumber(Integer unusableProductNumber) {
        this.unusableProductNumber = unusableProductNumber;
    }

    public Integer getQualityControlFinishNumber() {
        return qualityControlFinishNumber;
    }

    public void setQualityControlFinishNumber(Integer qualityControlFinishNumber) {
        this.qualityControlFinishNumber = qualityControlFinishNumber;
    }

    public Integer getSealBoxFinishNumber() {
        return sealBoxFinishNumber;
    }

    public void setSealBoxFinishNumber(Integer sealBoxFinishNumber) {
        this.sealBoxFinishNumber = sealBoxFinishNumber;
    }

    public Integer getSealBoxUnfinishNumber() {
        return sealBoxUnfinishNumber;
    }

    public void setSealBoxUnfinishNumber(Integer sealBoxUnfinishNumber) {
        this.sealBoxUnfinishNumber = sealBoxUnfinishNumber;
    }

    public Byte getSkuStatus() {
        return skuStatus;
    }

    public void setSkuStatus(Byte skuStatus) {
        this.skuStatus = skuStatus;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getSkuCreateTime() {
        return skuCreateTime;
    }

    public void setSkuCreateTime(Date skuCreateTime) {
        this.skuCreateTime = skuCreateTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getSkuUpdateTime() {
        return skuUpdateTime;
    }

    public void setSkuUpdateTime(Date skuUpdateTime) {
        this.skuUpdateTime = skuUpdateTime;
    }

    public Byte getIsExceptionCase() {
        return isExceptionCase;
    }

    public void setIsExceptionCase(Byte isExceptionCase) {
        this.isExceptionCase = isExceptionCase;
    }

    public String getSkuFloor() {
        return skuFloor;
    }

    public void setSkuFloor(String skuFloor) {
        this.skuFloor = skuFloor == null ? null : skuFloor.trim();
    }

    public String getReserved() {
        return reserved;
    }

    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
}