package com.brandslink.cloud.inbound.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  receive_sign_in
 * @author z
 * @date 2019-06-03 14:01:42
 */
@ApiModel(value ="ReceiveSignIn")
public class ReceiveSignIn implements Serializable {
	@ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "运单号")
    private String waybillId;
    
    @ApiModelProperty(value = "来源单号")
    private String sourceId;

    @ApiModelProperty(value = "仓库编码")
    private String warehouse;

    @ApiModelProperty(value = "运输方式")
    private String waybillType;
    
    @ApiModelProperty(value = "运输方式")
    private String waybillTypeName;

    @ApiModelProperty(value = "重量")
    private Double weight;

    @ApiModelProperty(value = "包裹数")
    private Integer parcelQuantity;

    @ApiModelProperty(value = "签到人")
    private String signInCreater;

    @ApiModelProperty(value = "签到人 id")
    private Integer signInId;

    @ApiModelProperty(value = "协同人名称")
    private String synergyName;

    @ApiModelProperty(value = "协同人id")
    private Integer synergyId;

    @ApiModelProperty(value = "收货台")
    private String receiveGoodNumber;

    @ApiModelProperty(value = "签到时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date signInTime;
    
    @ApiModelProperty(value = "来源类型 (1.采购入库  2. 销退入库 3. 调拨入库)")
    private String sourceType;
    
    @ApiModelProperty(value = "查询  开始时间")
    private String beginTime;
    @ApiModelProperty(value = "查询  结束时间")
    private String endTime;
    
    @ApiModelProperty(value = "仓库code集合")
    private List<String> warehouseCodes;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table receive_sign_in
     *
     * @mbg.generated 2019-06-03 14:01:42
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getWaybillId() {
        return waybillId;
    }

    public void setWaybillId(String waybillId) {
        this.waybillId = waybillId == null ? null : waybillId.trim();
    }

    public String getSourceId() {
        return sourceId;
    }

    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public String getWaybillTypeName() {
		return waybillTypeName;
	}

	public void setWaybillTypeName(String waybillTypeName) {
		this.waybillTypeName = waybillTypeName;
	}

	public String getWarehouse() {
        return warehouse;
    }

    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse == null ? null : warehouse.trim();
    }

    public String getWaybillType() {
        return waybillType;
    }

    public void setWaybillType(String waybillType) {
        this.waybillType = waybillType == null ? null : waybillType.trim();
    }

    public Double getWeight() {
        return weight;
    }

    public void setWeight(Double weight) {
        this.weight = weight;
    }

    public Integer getParcelQuantity() {
        return parcelQuantity;
    }

    public void setParcelQuantity(Integer parcelQuantity) {
        this.parcelQuantity = parcelQuantity;
    }

    public String getSignInCreater() {
        return signInCreater;
    }

    public void setSignInCreater(String signInCreater) {
        this.signInCreater = signInCreater == null ? null : signInCreater.trim();
    }

    public Integer getSignInId() {
        return signInId;
    }

    public void setSignInId(Integer signInId) {
        this.signInId = signInId;
    }

    public String getSynergyName() {
        return synergyName;
    }

    public void setSynergyName(String synergyName) {
        this.synergyName = synergyName == null ? null : synergyName.trim();
    }

    public Integer getSynergyId() {
        return synergyId;
    }

    public void setSynergyId(Integer synergyId) {
        this.synergyId = synergyId;
    }

    public String getReceiveGoodNumber() {
        return receiveGoodNumber;
    }

    public void setReceiveGoodNumber(String receiveGoodNumber) {
        this.receiveGoodNumber = receiveGoodNumber == null ? null : receiveGoodNumber.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getSignInTime() {
        return signInTime;
    }

    public void setSignInTime(Date signInTime) {
        this.signInTime = signInTime;
    }

	public String getBeginTime() {
		return beginTime;
	}

	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public List<String> getWarehouseCodes() {
		return warehouseCodes;
	}

	public void setWarehouseCodes(List<String> warehouseCodes) {
		this.warehouseCodes = warehouseCodes;
	}
    
    
    
    
}