package com.brandslink.cloud.inbound.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  receive_card_board_create
 * @author z
 * @date 2019-05-31 17:48:06
 */
@ApiModel(value ="ReceiveCardBoardCreate")
public class ReceiveCardBoardCreate implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "卡板号")
    private String cardBoardId;

    @ApiModelProperty(value = "来源单号(关联到货单 查询来源信息)")
    private String sourceId;

    @ApiModelProperty(value = "运单号")
    private String waybillId;

    @ApiModelProperty(value = "仓库编码")
    private String warehouseCode;

    @ApiModelProperty(value = "卡板 收货台")
    private String cardBoardCreateNumber;

    @ApiModelProperty(value = "卡板创建人")
    private String cardCreater;

    @ApiModelProperty(value = "卡板创建人 id")
    private Integer cardCreaterId;

    @ApiModelProperty(value = "卡板协同人")
    private String synergyName;

    @ApiModelProperty(value = "卡板协同人id")
    private Integer synergyId;

    @ApiModelProperty(value = "组板时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date cardStartTime;

    @ApiModelProperty(value = "满板时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date cardFinishTime;

    @ApiModelProperty(value = "商品详情单 创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "预留字段1")
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table receive_card_board_create
     *
     * @mbg.generated 2019-05-31 17:48:06
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCardBoardId() {
        return cardBoardId;
    }

    public void setCardBoardId(String cardBoardId) {
        this.cardBoardId = cardBoardId;
    }

    public String getSourceId() {
        return sourceId;
    }

    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    public String getWaybillId() {
        return waybillId;
    }

    public void setWaybillId(String waybillId) {
        this.waybillId = waybillId == null ? null : waybillId.trim();
    }

    public String getWarehouseCode() {
        return warehouseCode;
    }

    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode;
    }

    public String getCardBoardCreateNumber() {
        return cardBoardCreateNumber;
    }

    public void setCardBoardCreateNumber(String cardBoardCreateNumber) {
        this.cardBoardCreateNumber = cardBoardCreateNumber == null ? null : cardBoardCreateNumber.trim();
    }

    public String getCardCreater() {
        return cardCreater;
    }

    public void setCardCreater(String cardCreater) {
        this.cardCreater = cardCreater == null ? null : cardCreater.trim();
    }

    public Integer getCardCreaterId() {
        return cardCreaterId;
    }

    public void setCardCreaterId(Integer cardCreaterId) {
        this.cardCreaterId = cardCreaterId;
    }

    public String getSynergyName() {
        return synergyName;
    }

    public void setSynergyName(String synergyName) {
        this.synergyName = synergyName == null ? null : synergyName.trim();
    }

    public Integer getSynergyId() {
        return synergyId;
    }

    public void setSynergyId(Integer synergyId) {
        this.synergyId = synergyId;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCardStartTime() {
        return cardStartTime;
    }

    public void setCardStartTime(Date cardStartTime) {
        this.cardStartTime = cardStartTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCardFinishTime() {
        return cardFinishTime;
    }

    public void setCardFinishTime(Date cardFinishTime) {
        this.cardFinishTime = cardFinishTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getReserve1() {
        return reserve1;
    }

    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }
}