package com.brandslink.cloud.inbound.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.validation.constraints.NotBlank;

import org.springframework.format.annotation.DateTimeFormat;

import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonFormat;

import cn.afterturn.easypoi.excel.annotation.Excel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  selling_back
 * @author zc
 * @date 2019-06-26 10:10:52
 */
@ApiModel(value ="SellingBack")
public class SellingBack implements Serializable {
    @ApiModelProperty(value = "")
    @Excel(name = "序号",width = 10,orderNum = "0")
    private Integer id;

    @ApiModelProperty(value = "来源单号")
    @Excel(name = "来源单号",width = 20,orderNum = "4")
    private String sourceId;

    @ApiModelProperty(value = "销退收货单号")
    @Excel(name = "销退收货单号",width = 20,orderNum = "2")
    private String sellingBackId;

    @ApiModelProperty(value = "仓库编码")
    @Excel(name = "仓库",width = 20,orderNum = "1")
    private String warehouse;

    @ApiModelProperty(value = "单据状态(1 待收货/3 部分收货/4 收货完成)")
    @Excel(name = "单据状态",width = 20,orderNum = "3")
    private String status;

    @ApiModelProperty(value = "退货类型(1客户退货/2超时退回/3机场安检不过/4其它)")
    @Excel(name = "退货类型",width = 20,orderNum = "5")
    private String sellingBackType;

    @ApiModelProperty(value = "平台")
    @Excel(name = "平台",width = 10,orderNum = "6")
    private String platform;

    @ApiModelProperty(value = "运单号")
    @Excel(name = "运单号",width = 20,orderNum = "7")
    private String waybillId;

    @ApiModelProperty(value = "物流商")
    @Excel(name = "物流商",width = 20,orderNum = "8")
    private String logistics;

    @ApiModelProperty(value = "邮寄方式")
    private String mailingMethod;

    @ApiModelProperty(value = "包裹号")
    private String parcelId;

    @ApiModelProperty(value = "接收人")
    @Excel(name = "接收人",width = 20,orderNum = "9")
    private String receiver;

    @ApiModelProperty(value = "接收人id")
    private Integer receiverId;

    @ApiModelProperty(value = "接收时间")
    @Excel(name = "接收时间",width = 20,orderNum = "10")
    private String receiveTime;
    
    @ApiModelProperty(value = "创建时间")
    private String createTime;

    
    @ApiModelProperty(value = "备注")
    @Excel(name = "备注",width = 20,orderNum = "11")
    private String remark;

    @ApiModelProperty(value = "客户")
	private String customer;
    
    @ApiModelProperty(value = "客户名称")
    private String customerName;
    
    @ApiModelProperty(value = "质检方式")
	private String qualityType;
    
    @ApiModelProperty(value = "时间查询  开始时间")
    @JSONField(serialize=false)
    private String beginTime;
    
    @ApiModelProperty(value = "时间查询  结束时间")
    @JSONField(serialize=false)
    private String endTime;
    
    @ApiModelProperty(value = "排序 asc 升序 desc 降序")
    private String orderStatus;
    
    private Object statisticsMap;
    
    @ApiModelProperty(value = "仓库code集合")
    private List<String> warehouseCodes;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table selling_back
     *
     * @mbg.generated 2019-06-26 10:10:52
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSourceId() {
        return sourceId;
    }

    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    public String getSellingBackId() {
        return sellingBackId;
    }

    public void setSellingBackId(String sellingBackId) {
        this.sellingBackId = sellingBackId == null ? null : sellingBackId.trim();
    }

    public String getWarehouse() {
        return warehouse;
    }

    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse == null ? null : warehouse.trim();
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public String getSellingBackType() {
        return sellingBackType;
    }

    public void setSellingBackType(String sellingBackType) {
        this.sellingBackType = sellingBackType == null ? null : sellingBackType.trim();
    }

    public String getPlatform() {
        return platform;
    }

    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    public String getWaybillId() {
        return waybillId;
    }

    public void setWaybillId(String waybillId) {
        this.waybillId = waybillId == null ? null : waybillId.trim();
    }

    public String getLogistics() {
        return logistics;
    }

    public void setLogistics(String logistics) {
        this.logistics = logistics == null ? null : logistics.trim();
    }

    public String getMailingMethod() {
        return mailingMethod;
    }

    public void setMailingMethod(String mailingMethod) {
        this.mailingMethod = mailingMethod == null ? null : mailingMethod.trim();
    }

    public String getParcelId() {
        return parcelId;
    }

    public void setParcelId(String parcelId) {
        this.parcelId = parcelId == null ? null : parcelId.trim();
    }

    public String getReceiver() {
        return receiver;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    public Integer getReceiverId() {
        return receiverId;
    }

    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    public String getReceiveTime() {
        return receiveTime;
    }

    public void setReceiveTime(String receiveTime) {
        this.receiveTime = receiveTime;
    }
    
    public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	public String getBeginTime() {
		return beginTime;
	}

	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public Object getStatisticsMap() {
		return statisticsMap;
	}

	public void setStatisticsMap(Object statisticsMap) {
		this.statisticsMap = statisticsMap;
	}

	public String getOrderStatus() {
		return orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	public List<String> getWarehouseCodes() {
		return warehouseCodes;
	}

	public void setWarehouseCodes(List<String> warehouseCodes) {
		this.warehouseCodes = warehouseCodes;
	}

	public String getCustomer() {
		return customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	
	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getQualityType() {
		return qualityType;
	}

	public void setQualityType(String qualityType) {
		this.qualityType = qualityType;
	}
	
    
}