package com.brandslink.cloud.inbound.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  selling_back_detail
 * @author zc
 * @date 2019-06-26 10:10:52
 */
@ApiModel(value ="SellingBackDetail")
public class SellingBackDetail implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "运单号")
    private String waybillId;

    @ApiModelProperty(value = "sku")
    private String sku;

    @ApiModelProperty(value = "计划数")
    private Integer plannedQuantity;

    @ApiModelProperty(value = "收货数")
    private Integer deliveryQuantity;

    @ApiModelProperty(value = "差异数")
    private Integer differQuantity;

    @ApiModelProperty(value = "质检人")
    private String qcCreater;

    @ApiModelProperty(value = "质检人id")
    private Integer qcCreaterId;

    @ApiModelProperty(value = "质检时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date qcTime;

    @ApiModelProperty(value = "图片地址")
    private String pictureUrl;
    
    @ApiModelProperty(value = "产品名称")
    private String productName;
    
    
    private SellingBack sellingBack;
    
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table selling_back_detail
     *
     * @mbg.generated 2019-06-26 10:10:52
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getWaybillId() {
        return waybillId;
    }

    public void setWaybillId(String waybillId) {
        this.waybillId = waybillId == null ? null : waybillId.trim();
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    public Integer getPlannedQuantity() {
        return plannedQuantity;
    }

    public void setPlannedQuantity(Integer plannedQuantity) {
        this.plannedQuantity = plannedQuantity;
    }

    public Integer getDeliveryQuantity() {
        return deliveryQuantity;
    }

    public void setDeliveryQuantity(Integer deliveryQuantity) {
        this.deliveryQuantity = deliveryQuantity;
    }

    public Integer getDifferQuantity() {
        return differQuantity;
    }

    public void setDifferQuantity(Integer differQuantity) {
        this.differQuantity = differQuantity;
    }

    public String getQcCreater() {
        return qcCreater;
    }

    public void setQcCreater(String qcCreater) {
        this.qcCreater = qcCreater == null ? null : qcCreater.trim();
    }

    public Integer getQcCreaterId() {
        return qcCreaterId;
    }

    public void setQcCreaterId(Integer qcCreaterId) {
        this.qcCreaterId = qcCreaterId;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getQcTime() {
        return qcTime;
    }

    public void setQcTime(Date qcTime) {
        this.qcTime = qcTime;
    }

	public String getPictureUrl() {
		return pictureUrl;
	}

	public void setPictureUrl(String pictureUrl) {
		this.pictureUrl = pictureUrl;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public SellingBack getSellingBack() {
		return sellingBack;
	}

	public void setSellingBack(SellingBack sellingBack) {
		this.sellingBack = sellingBack;
	}
    
    
    
    
    
}